version: '2.0'
services:
    nats:
        image: nats:2.3
        ports:
            - "4222"
            - "6222"
            - "8222"
        command: [ "-js" ]
    redis:
        image: redis:6.2
        ports:
            - "6379"
    node-red:
        # image: sax1johno/node-red-base
        build: .
        # container_name: "node-red"
        ports:
            - '80'
        restart: unless-stopped
        environment:
            PROJECTS: "true"
